Bush/Models/ApplicationDbContex.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Bush.Models
{
    public class ApplicationDbContex : DbContext
    {
        public ApplicationDbContex() : base("Data Source=EYTECLAP5\\MSSQLSERVER2019;" +
            "Initial Catalog=Emp;Integrated Security=True;Pooling=False") { }
        public DbSet<Empolyee> empolyees { get; set; }
       
    }
}

Bush/Models/Empolyee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bush.Models
{
    public class Empolyee
    {
        public int id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public int salary { get; set; }
        public string gender { get; set; }
        public string Maneger { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
    }
}

Bush/Controllers/EmpolyeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bush.Models;

namespace Bush.Controllers
{
    public class EmpolyeesController : Controller
    {  
       public ApplicationDbContex db = new ApplicationDbContex();
 
        public ActionResult Index()
        {
            return View(db.empolyees.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empolyee empolyee = db.empolyees.Find(id);
            if (empolyee == null)
            {
                return HttpNotFound();
            }
            return View(empolyee);
        }

          public ActionResult Create()
        {
           
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,age,salary,gender,Maneger,Department,Role")] Empolyee empolyee)
        {
            List<Empolyee> emp = db.empolyees.ToList();

            ViewBag.Emp1 = new SelectList(emp, "name", "name");

            if (ModelState.IsValid)
            {
             
                    db.empolyees.Add(empolyee);
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }

            return View(empolyee);
        }


        public ActionResult Edit(int? id)
        {
            List<Empolyee> emp = db.empolyees.ToList();
            ViewBag.Emp1 = new SelectList(emp, "name", "name");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empolyee empolyee = db.empolyees.Find(id);
            if (empolyee == null)
            {
                return HttpNotFound();
            }
            return View(empolyee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Edit([Bind(Include = "id,name,age,salary,gender,Maneger,Department,Role")] Empolyee empolyee)
        {
           
            if (ModelState.IsValid)
            {
                
                db.Entry(empolyee).State = EntityState.Modified;
                var manager = db.empolyees.Where(e => e.name == empolyee.Maneger).FirstOrDefault();
                if (manager.Maneger == empolyee.name)
                {
                    throw new Exception("Circular manager found");
                }
                else
                {
                    if (empolyee.name != empolyee.Maneger)
                    {

                        db.SaveChanges();
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        return HttpNotFound("Emplyee name and Manger name is same ");
                    }
                }
            }
            return View(empolyee);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empolyee empolyee = db.empolyees.Find(id);
            if (empolyee == null)
            {
                return HttpNotFound();
            }
            return View(empolyee);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empolyee empolyee = db.empolyees.Find(id);
            db.empolyees.Remove(empolyee); 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bush/Views/Empolyees/Create.cshtml
@model Bush.Models.Empolyee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Empolyee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Maneger, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Maneger, ViewBag.Emp1 as SelectList, "--select--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Maneger, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
        @* <div class="col-md-10">
            @{
                List<SelectListItem> lst = new List<SelectListItem>();
                lst.Add(new SelectListItem { Text = "Male", Value = "Male" });
                lst.Add(new SelectListItem { Text = "Female", Value = "Female" });
            }
            @Html.DropDownListFor(model => model.gender, lst, "Select gender", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.gender,"", new { @class = "text-danger" })
            </div>*@
        <div class="col-md-10">
            @Html.RadioButton(name: "gender", value: "Male") Male

            @Html.RadioButton(name: "gender", value: "Female") Female

            @Html.RadioButton(name: "gender", value: "Other") Other
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                List<SelectListItem> lis = new List<SelectListItem>();
                lis.Add(new SelectListItem { Text = "MR", Value = "MR" });
                lis.Add(new SelectListItem { Text = "HR", Value = "HR" });
                lis.Add(new SelectListItem { Text = "IT", Value = "IT" });
                lis.Add(new SelectListItem { Text = "AC", Value = "AC" });
                lis.Add(new SelectListItem { Text = "EC", Value = "EC" });
            }
            @Html.DropDownListFor(model => model.Department, lis, "Select Post", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                List<SelectListItem> lie = new List<SelectListItem>();
                lie.Add(new SelectListItem { Text = "Developer", Value = "Developer" });
                lie.Add(new SelectListItem { Text = "Project Maneger", Value = "Project Maneger" });
                lie.Add(new SelectListItem { Text = "QA", Value = "QA" });
                lie.Add(new SelectListItem { Text = "Data Analyst", Value = "Data Analyst" });
                lie.Add(new SelectListItem { Text = "Tranni", Value = "Tranni" });
            }
            @Html.DropDownListFor(model => model.Role, lie, "Select Role", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
                    }

<button >
    @Html.ActionLink("Back to List", "Index")
</button>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

   }

Bush/Views/Empolyees/Delete.cshtml
@model Bush.Models.Empolyee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empolyee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maneger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maneger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>


        <button> @Html.ActionLink("Back to List", "Index")</button>
    }
</div>

Bush/Views/Empolyees/Details.cshtml
@model Bush.Models.Empolyee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empolyee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maneger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maneger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>

</div>
<p>
    <button class="btn btn-outline-success"> @Html.ActionLink("Edit", "Edit", new { id = Model.id })</button>
    @*<button> @Html.ActionLink("Back to List", "Index")</button>*@
</p>

Bush/Views/Empolyees/Edit.cshtml
@model Bush.Models.Empolyee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Empolyee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="col-md-10">
                @Html.RadioButton(name: "gender", value: "Male") Male

                @Html.RadioButton(name: "gender", value: "Female") Female

                @Html.RadioButton(name: "gender", value: "Other") Other
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Maneger, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Maneger, ViewBag.Emp1 as SelectList, "--select--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Maneger, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                List<SelectListItem> lis = new List<SelectListItem>();
                lis.Add(new SelectListItem { Text = "MR", Value = "MR" });
                lis.Add(new SelectListItem { Text = "HR", Value = "HR" });
                lis.Add(new SelectListItem { Text = "IT", Value = "IT" });
                lis.Add(new SelectListItem { Text = "AC", Value = "AC" });
                lis.Add(new SelectListItem { Text = "EC", Value = "EC" });
            }
            @Html.DropDownListFor(model => model.Department, lis, "Select Post", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                List<SelectListItem> lie = new List<SelectListItem>();
                lie.Add(new SelectListItem { Text = "Developer", Value = "Developer" });
                lie.Add(new SelectListItem { Text = "Project Maneger", Value = "Project Maneger" });
                lie.Add(new SelectListItem { Text = "QA", Value = "QA" });
                lie.Add(new SelectListItem { Text = "Data Analyst", Value = "Data Analyst" });
                lie.Add(new SelectListItem { Text = "Tranni", Value = "Tranni" });
            }
            @Html.DropDownListFor(model => model.Role, lie, "Select Role", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />        
        </div>
    </div>
</div>
}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bush/Views/Empolyees/Index.cshtml
@model IEnumerable<Bush.Models.Empolyee>

@{
    ViewBag.Title = "Index";
}

<h2>Employees List</h2>


@*<button>
    @html.actionlink("create new", "create")
</button>*@



<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Maneger)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem=> item.Maneger)   
        </td>
        <td>
            @Html.DisplayFor(modelItem=> item.Department)
        </td>
        <td>
            @Html.DisplayFor(modelItem=> item.Role)
        </td>
        <td>

            <button  class="btn btn-outline-primary"> @Html.ActionLink("Details", "Details", new { id = item.id })</button>     |

            <button  class="btn btn-outline-success"> @Html.ActionLink("Edit", "Edit", new { id = item.id })</button>        |

            <button  class="btn btn-outline-danger">@Html.ActionLink("Delete", "Delete", new { id = item.id })</button>
        </td>
    </tr>
}

</table>

Bush/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee", "Index", "Empolyees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   @* <li>@Html.ActionLink("Employee", "Index", "Empolyees")</li>*@
                    <li>@Html.ActionLink("Create New", "create", "Empolyees")</li>
                   @* <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Date - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>